ionstatbuf /var/containers/Bundle/Application/7A99BF06-E4A8-4703-9333-3D1DBA2E5D02/ClientTest.app/ClientTest
     ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
ionlengthlstat /var/mobile/Library/Fonts/AddedFontCache.plist
ionlengthlstat /System
ionlengthlstat /System/Library
ionlengthlstat /System/Library/CoreServices
ionlengthlstat /System/Library/CoreServices/CoreGlyphs.bundle
ionstatbuf /System/Library/CoreServices/CoreGlyphs.bundle
ionstatbuf /System/Library/CoreServices/CoreGlyphs.bundle
ionlengthlstat /System/Library/PrivateFrameworks
ionlengthlstat /System/Library/PrivateFrameworks/UIKitCore.framework
ionlengthlstat /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
ionstatbuf /System/Library/PrivateFrameworks/UIKitCore.framework
ionstatbuf /System/Library/PrivateFrameworks/UIKitCore.framework
ionstatbuf /System/Library/PrivateFrameworks/UIKitCore.framework
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
ionstatbuf /System/Library/PrivateFrameworks/CoreMaterial.framework
ionstatbuf /System/Library/PrivateFrameworks/CoreMaterial.framework
ionstatbuf /System/Library/PrivateFrameworks/CoreMaterial.framework/CoreMaterial
ionlengthlstat /System/Library/PrivateFrameworks/CoreMaterial.framework
ionstatbuf /System/Library/PrivateFrameworks/CoreMaterial.framework
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Documents/.cache1
ionstatbuf /var/containers/Bundle/Application/7A99BF06-E4A8-4703-9333-3D1DBA2E5D02/ClientTest.app
ionlengthfopen /private/var/containers/Bundle/Application/7A99BF06-E4A8-4703-9333-3D1DBA2E5D02/.meta
ionlengthfopen /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Documents/.cache1
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
ionFFFstatfs /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Documents
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
ionstatbuf /var/db/timezone/icutz
ionstatbuf /var/db/timezone/icutz/icutz44l.dat
ionstatbuf /var/db/timezone/icutz/icutz44l.dat
ionlengthlstat /var/mobile/Library/Caches/com.apple.itunesstored/url-resolution.plist
ionlengthlstat /var/mobile/Library/Caches/com.apple.keyboards/version
ionlengthlstat /var/mobile/Library/Caches/GeoServices/SearchAttribution.pbd
ionlengthlstat /var/mobile/Library/Caches/Checkpoint.plist
ionlengthlstat /private/var/Managed Preferences/mobile/.GlobalPreferences.plist
ionlengthlstat /private/var/Managed Preferences/mobile/com.apple.webcontentfilter.plist
ionlengthlstat /private/var/mobile
ionlengthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64
ionlengthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s
ionlengthlstat /System/Library/Caches/fps/lskd.rl
ionlengthlstat /var/mobile/Library/Caches/DateFormats.plist
ionlengthlstat /var/mobile/Library/Caches/GeoServices/Resources/altitude-551.xml
ionlengthlstat /var/mobile/Library/Caches/GeoServices/Resources/autonavi-1.png
ionlengthlstat /var/mobile/Library/Caches/GeoServices/Resources/autonavi-1@2x.png
ionlengthlstat /var/mobile/Library/Caches/GeoServices/Resources/supportedCountriesDirections-12.plist
ionlengthlstat /etc/group
ionlengthlstat /etc/hosts
ionlengthlstat /etc/passwd
ionlengthlstat /System/Library/Backup/Domains.plist
ionlengthlstat /System/Library/Spotlight/domains.plist
ionlengthlstat /Library/Managed Preferences/mobile/.GlobalPreferences.plist
ionlengthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64
ionlengthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e
ionlengthlstat /System/Library/PrivateFrameworks/AppSupport.framework/Info.plist
ionlengthlstat /System/Library/Filesystems/hfs.fs/Info.plist
ionlengthlstat /System/Library/Caches/apticket.der
ionlengthlstat /System/Library/CoreServices/SystemVersion.plist
ionlengthlstat /System/Library/CoreServices/powerd.bundle/Info.plist
ionlengthlstat /System/Library/Lockdown/iPhoneDeviceCA.pem
ionlengthlstat /System/Library/Lockdown/iPhoneDebug.pem
ionlengthlstat /System/Library/LaunchDaemons/com.apple.powerd.plist
ionlengthlstat /System/Library/LaunchDaemons/bootps.plist
ionlengthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e
ionlengthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s
ionlengthlstat /System/Library/Caches/fps/lskd.rl
ionlengthlstat /var/mobile/Library/Caches/GeoServices/Resources/autonavi-1.png
ionlengthlstat /var/mobile/Library/Caches/GeoServices/Resources/autonavi-1@2x.png
ionlengthlstat /var/mobile/Library/Caches/GeoServices/Resources/supportedCountriesDirections-12.plist
ionlengthlstat /private/var/wireless/Library/LASD/lasdcdma.db
ionlengthlstat /private/var/wireless/Library/LASD/lasdgsm.db
ionlengthlstat /private/var/wireless/Library/LASD/lasdlte.db
ionlengthlstat /private/var/wireless/Library/LASD/lasdscdma.db
ionlengthlstat /private/var/wireless/Library/LASD/lasdumts.db
ionlengthlstat /private/var/run/printd
ionlengthlstat /private/var/run/syslog
ionlengthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e
ionstatbuf /dev/random
ionlengthlstat /dev/random
ionstatbuf /private/var/run/printd
ionlengthlstat /private/var/run/printd
ionlengthlstat /private/var/run/printd
ionstatbuf /private/var/run/syslog
ionlengthlstat /private/var/run/syslog
ionlengthlstat /private/var/run/syslog
ionstatbuf /private/var/mobile/Library/UserConfigurationProfiles/PublicInfo/MCMeta.plist
ionlengthlstat /private/var/mobile/Library/UserConfigurationProfiles/PublicInfo/MCMeta.plist
ionstatbuf /private/var/mobile/Library/Preferences
ionlengthlstat /private/var/mobile/Library/Preferences
ionlengthlstat /private/var/mobile/Library/Preferences
ionstatbuf /Library/Managed Preferences/mobile/.GlobalPreferences.plist
ionlengthlstat /Library/Managed Preferences/mobile/.GlobalPreferences.plist
ionlengthlstat /Library/Managed Preferences/mobile/.GlobalPreferences.plist
ionstatbuf /Library/Managed Preferences/mobile/com.apple.webcontentfilter.plist
ionlengthlstat /Library/Managed Preferences/mobile/com.apple.webcontentfilter.plist
ionlengthlstat /Library/Managed Preferences/mobile/com.apple.webcontentfilter.plist
ionstatbuf /private/var/containers/Data/System/com.apple.geod/.com.apple.mobile_container_manager.metadata.plist
ionlengthlstat /private/var/containers/Data/System/com.apple.geod/.com.apple.mobile_container_manager.metadata.plist
ionlengthlstat /private/var/containers/Data/System/com.apple.geod/.com.apple.mobile_container_manager.metadata.plist
ionstatbuf /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.lsd.iconscache/.com.apple.mobile_container_manager.metadata.plist
ionlengthlstat /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.lsd.iconscache/.com.apple.mobile_container_manager.metadata.plist
ionlengthlstat /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.lsd.iconscache/.com.apple.mobile_container_manager.metadata.plist
ionstatbuf /private/var/mobile/Library/Caches/DateFormats.plist
ionlengthlstat /private/var/mobile/Library/Caches/DateFormats.plist
ionlengthlstat /private/var/mobile/Library/Caches/DateFormats.plist
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/ActiveTileGroup.pbd
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/ActiveTileGroup.pbd
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/ActiveTileGroup.pbd
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Experiments.pbd
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Experiments.pbd
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Experiments.pbd
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Resources/DetailedLandCoverPavedArea-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/DetailedLandCoverPavedArea-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/DetailedLandCoverPavedArea-1@2x.png
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Resources/LandCoverGradient16-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/LandCoverGradient16-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/LandCoverGradient16-1@2x.png
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadHighway-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadHighway-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadHighway-1@2x.png
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadLocalRoad-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadLocalRoad-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadLocalRoad-1@2x.png
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Resources/altitude-551.xml
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/altitude-551.xml
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/altitude-551.xml
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Resources/autonavi-1.png
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Resources/autonavi-1@2x.png
ionstatbuf /private/var/mobile/Library/Caches/GeoServices/Resources/night-DetailedLandCoverSand-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/night-DetailedLandCoverSand-1@2x.png
ionlengthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/night-DetailedLandCoverSand-1@2x.png
ionstatbuf /private/var/mobile/Library/Carrier Bundles/Overlay
ionlengthlstat /private/var/mobile/Library/Carrier Bundles/Overlay
ionlengthlstat /private/var/mobile/Library/Carrier Bundles/Overlay
ionstatbuf /private/var/mobile/Library/Operator Bundle.bundle
ionlengthlstat /private/var/mobile/Library/Operator Bundle.bundle
ionlengthlstat /private/var/mobile/Library/Operator Bundle.bundle
ionstatbuf /private/var/mobile/Library
ionlengthlstat /private/var/mobile/Library
ionlengthlstat /private/var/mobile/Library
ionstatbuf /private/var/mobile
ionlengthlstat /private/var/mobile
ionlengthlstat /private/var/mobile
ionstatbuf /private/var
ionlengthlstat /private/var
ionlengthlstat /private/var
ionstatbuf /var/db/timezone/localtime
ionlengthlstat /var/db/timezone/localtime
ionlengthlstat /var/db/timezone/localtime
ionlengthlstat /System/Library/CoreServices/SystemVersion.plist
ionlengthlstat /usr/local
ionlengthlstat /usr
ionlengthlstat /usr/local/
ionlengthlstat /private
ionlengthlstat /var/root
ionlengthlstat /var/mobile
ionlengthlstat /var/root/
ionlengthlstat /var/wireless
ionstatbuf /Applications/Cydia.app
ionstatbuf /var/mobile/Library/Caches/com.xxtouch.XXTExplorer
ionstatbuf /Applications/AWZ.app
ionlengthfopen /Applications/AWZ.app
ionstatbuf /Applications/NZT.app
ionlengthfopen /Applications/NZT.app
ionstatbuf /Applications/igvx.app
ionlengthfopen /Applications/igvx.app
ionstatbuf /Applications/TouchElf.app
ionlengthfopen /Applications/TouchElf.app
ionstatbuf /Applications/TouchSprite.app
ionlengthfopen /Applications/TouchSprite.app
ionstatbuf /Applications/WujiVPN.app
ionlengthfopen /Applications/WujiVPN.app
ionstatbuf /Applications/RST.app
ionlengthfopen /Applications/RST.app
ionstatbuf /Applications/Forge9.app
ionlengthfopen /Applications/Forge9.app
ionstatbuf /Applications/Forge.app
ionlengthfopen /Applications/Forge.app
ionstatbuf /Applications/GFaker.app
ionlengthfopen /Applications/GFaker.app
ionstatbuf /Applications/hdfakerset.app
ionlengthfopen /Applications/hdfakerset.app
ionstatbuf /Applications/Pranava.app
ionlengthfopen /Applications/Pranava.app
ionstatbuf /Applications/iG.app
ionlengthfopen /Applications/iG.app
ionstatbuf /Applications/HiddenApi.app
ionlengthfopen /Applications/HiddenApi.app
ionstatbuf /Applications/Xgen.app
ionlengthfopen /Applications/Xgen.app
ionstatbuf /Applications/BirdFaker9.app
ionlengthfopen /Applications/BirdFaker9.app
ionstatbuf /Applications/VPNMasterPro.app
ionlengthfopen /Applications/VPNMasterPro.app
ionstatbuf /Applications/GuizmOVPN.app
ionlengthfopen /Applications/GuizmOVPN.app
ionstatbuf /Applications/OTRLocation.app
ionlengthfopen /Applications/OTRLocation.app
ionstatbuf /Applications/rwx.app
ionlengthfopen /Applications/rwx.app
ionstatbuf /Applications/FakeMyLocation.app
ionlengthfopen /Applications/FakeMyLocation.app
ionstatbuf /Applications/anylocation.app
ionlengthfopen /Applications/anylocation.app
ionstatbuf /Applications/location360pro.app
ionlengthfopen /Applications/location360pro.app
ionstatbuf /Applications/xGPS.app
ionlengthfopen /Applications/xGPS.app
ionstatbuf /Applications/007gaiji.app
ionlengthfopen /Applications/007gaiji.app
ionstatbuf /Applications/ALS.app
ionlengthfopen /Applications/ALS.app
ionstatbuf /Applications/AXJ.app
ionlengthfopen /Applications/AXJ.app
ionstatbuf /Applications/serialudid.app
ionlengthfopen /Applications/serialudid.app
ionstatbuf /Applications/BirdFaker.app
ionlengthfopen /Applications/BirdFaker.app
ionstatbuf /Applications/zorro.app
ionlengthfopen /Applications/zorro.app
ionstatbuf /Applications/YOY.app
ionlengthfopen /Applications/YOY.app
ionstatbuf /System/Library/Frameworks/CFNetwork.framework
ionstatbuf /System/Library/Frameworks/CFNetwork.framework
ionstatbuf /System/Library/Frameworks/CFNetwork.framework/CFNetwork
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
ionstatbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
