statbuf /var/containers/Bundle/Application/7A99BF06-E4A8-4703-9333-3D1DBA2E5D02/ClientTest.app/ClientTest
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
engthlstat /var/mobile/Library/Fonts/AddedFontCache.plist
engthlstat /System
engthlstat /System/Library
engthlstat /System/Library/CoreServices
engthlstat /System/Library/CoreServices/CoreGlyphs.bundle
statbuf /System/Library/CoreServices/CoreGlyphs.bundle
statbuf /System/Library/CoreServices/CoreGlyphs.bundle
engthlstat /System/Library/PrivateFrameworks
engthlstat /System/Library/PrivateFrameworks/UIKitCore.framework
engthlstat /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
statbuf /System/Library/PrivateFrameworks/UIKitCore.framework
statbuf /System/Library/PrivateFrameworks/UIKitCore.framework
statbuf /System/Library/PrivateFrameworks/UIKitCore.framework
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
statbuf /var/containers/Bundle/Application/7A99BF06-E4A8-4703-9333-3D1DBA2E5D02/ClientTest.app
engthlstat /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
statbuf /System/Library/PrivateFrameworks/UIKitCore.framework
statbuf /System/Library/PrivateFrameworks/CoreMaterial.framework
statbuf /System/Library/PrivateFrameworks/CoreMaterial.framework
statbuf /System/Library/PrivateFrameworks/CoreMaterial.framework/CoreMaterial
engthlstat /System/Library/PrivateFrameworks/CoreMaterial.framework
statbuf /System/Library/PrivateFrameworks/CoreMaterial.framework
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Documents/.cache1
engthfopen /private/var/containers/Bundle/Application/7A99BF06-E4A8-4703-9333-3D1DBA2E5D02/.meta
engthlstat /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
statbuf /System/Library/PrivateFrameworks/UIKitCore.framework
engthfopen /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Documents/.cache1
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
FFFstatfs /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Documents
statbuf /System/Library/PrivateFrameworks/DataDetectorsCore.framework
statbuf /System/Library/PrivateFrameworks/DataDetectorsCore.framework
statbuf /System/Library/PrivateFrameworks/DataDetectorsCore.framework/DataDetectorsCore
statbuf /System/Library/PrivateFrameworks/DataDetectorsCore.framework/com.apple.datadetectorscore.cache.urlifier.system
fstatfs /System/Library/PrivateFrameworks/DataDetectorsCore.framework/com.apple.datadetectorscore.cache.urlifier.system
statbuf /usr/share/langid/langid.inv
statbuf /System/Library/PrivateFrameworks/DataDetectorsCore.framework/com.apple.datadetectorscore.cache.urlifier.system
fstatfs /System/Library/PrivateFrameworks/DataDetectorsCore.framework/com.apple.datadetectorscore.cache.urlifier.system
statbuf /System/Library/PrivateFrameworks/CoreNLP.framework
statbuf /System/Library/PrivateFrameworks/CoreNLP.framework
statbuf /System/Library/PrivateFrameworks/CoreNLP.framework/CoreNLP
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
statbuf /var/db/timezone/icutz
statbuf /var/db/timezone/icutz/icutz44l.dat
statbuf /var/db/timezone/icutz/icutz44l.dat
engthlstat /var/mobile/Library/Caches/com.apple.itunesstored/url-resolution.plist
engthlstat /var/mobile/Library/Caches/com.apple.keyboards/version
engthlstat /var/mobile/Library/Caches/GeoServices/SearchAttribution.pbd
engthlstat /var/mobile/Library/Caches/Checkpoint.plist
engthlstat /private/var/Managed Preferences/mobile/.GlobalPreferences.plist
engthlstat /private/var/Managed Preferences/mobile/com.apple.webcontentfilter.plist
engthlstat /private/var/mobile
engthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64
engthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s
engthlstat /System/Library/Caches/fps/lskd.rl
engthlstat /var/mobile/Library/Caches/DateFormats.plist
engthlstat /var/mobile/Library/Caches/GeoServices/Resources/altitude-551.xml
engthlstat /var/mobile/Library/Caches/GeoServices/Resources/autonavi-1.png
engthlstat /var/mobile/Library/Caches/GeoServices/Resources/autonavi-1@2x.png
engthlstat /var/mobile/Library/Caches/GeoServices/Resources/supportedCountriesDirections-12.plist
engthlstat /etc/group
engthlstat /etc/hosts
engthlstat /etc/passwd
engthlstat /System/Library/Backup/Domains.plist
engthlstat /System/Library/Spotlight/domains.plist
engthlstat /Library/Managed Preferences/mobile/.GlobalPreferences.plist
engthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64
engthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e
engthlstat /System/Library/PrivateFrameworks/AppSupport.framework/Info.plist
engthlstat /System/Library/Filesystems/hfs.fs/Info.plist
engthlstat /System/Library/Caches/apticket.der
engthlstat /System/Library/CoreServices/SystemVersion.plist
engthlstat /System/Library/CoreServices/powerd.bundle/Info.plist
engthlstat /System/Library/Lockdown/iPhoneDeviceCA.pem
engthlstat /System/Library/Lockdown/iPhoneDebug.pem
engthlstat /System/Library/LaunchDaemons/com.apple.powerd.plist
engthlstat /System/Library/LaunchDaemons/bootps.plist
engthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e
engthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_armv7s
engthlstat /System/Library/Caches/fps/lskd.rl
engthlstat /var/mobile/Library/Caches/GeoServices/Resources/autonavi-1.png
engthlstat /var/mobile/Library/Caches/GeoServices/Resources/autonavi-1@2x.png
engthlstat /var/mobile/Library/Caches/GeoServices/Resources/supportedCountriesDirections-12.plist
engthlstat /private/var/wireless/Library/LASD/lasdcdma.db
engthlstat /private/var/wireless/Library/LASD/lasdgsm.db
engthlstat /private/var/wireless/Library/LASD/lasdlte.db
engthlstat /private/var/wireless/Library/LASD/lasdscdma.db
engthlstat /private/var/wireless/Library/LASD/lasdumts.db
engthlstat /private/var/run/printd
默认2021-07-.83729126 16:36:070800lengthlstat /private/var/run/syslog
engthlstat /System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e
statbuf /dev/random
engthlstat /dev/random
statbuf /private/var/run/printd
engthlstat /private/var/run/printd
engthlstat /private/var/run/printd
statbuf /private/var/run/syslog
engthlstat /private/var/run/syslog
engthlstat /private/var/run/syslog
statbuf /private/var/mobile/Library/UserConfigurationProfiles/PublicInfo/MCMeta.plist
engthlstat /private/var/mobile/Library/UserConfigurationProfiles/PublicInfo/MCMeta.plist
statbuf /private/var/mobile/Library/Preferences
engthlstat /private/var/mobile/Library/Preferences
engthlstat /private/var/mobile/Library/Preferences
statbuf /Library/Managed Preferences/mobile/.GlobalPreferences.plist
engthlstat /Library/Managed Preferences/mobile/.GlobalPreferences.plist
engthlstat /Library/Managed Preferences/mobile/.GlobalPreferences.plist
statbuf /Library/Managed Preferences/mobile/com.apple.webcontentfilter.plist
engthlstat /Library/Managed Preferences/mobile/com.apple.webcontentfilter.plist
engthlstat /Library/Managed Preferences/mobile/com.apple.webcontentfilter.plist
statbuf /private/var/containers/Data/System/com.apple.geod/.com.apple.mobile_container_manager.metadata.plist
engthlstat /private/var/containers/Data/System/com.apple.geod/.com.apple.mobile_container_manager.metadata.plist
engthlstat /private/var/containers/Data/System/com.apple.geod/.com.apple.mobile_container_manager.metadata.plist
statbuf /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.lsd.iconscache/.com.apple.mobile_container_manager.metadata.plist
engthlstat /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.lsd.iconscache/.com.apple.mobile_container_manager.metadata.plist
engthlstat /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.lsd.iconscache/.com.apple.mobile_container_manager.metadata.plist
statbuf /private/var/mobile/Library/Caches/DateFormats.plist
engthlstat /private/var/mobile/Library/Caches/DateFormats.plist
engthlstat /private/var/mobile/Library/Caches/DateFormats.plist
statbuf /private/var/mobile/Library/Caches/GeoServices/ActiveTileGroup.pbd
engthlstat /private/var/mobile/Library/Caches/GeoServices/ActiveTileGroup.pbd
engthlstat /private/var/mobile/Library/Caches/GeoServices/ActiveTileGroup.pbd
statbuf /private/var/mobile/Library/Caches/GeoServices/Experiments.pbd
engthlstat /private/var/mobile/Library/Caches/GeoServices/Experiments.pbd
engthlstat /private/var/mobile/Library/Caches/GeoServices/Experiments.pbd
statbuf /private/var/mobile/Library/Caches/GeoServices/Resources/DetailedLandCoverPavedArea-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/DetailedLandCoverPavedArea-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/DetailedLandCoverPavedArea-1@2x.png
statbuf /private/var/mobile/Library/Caches/GeoServices/Resources/LandCoverGradient16-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/LandCoverGradient16-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/LandCoverGradient16-1@2x.png
statbuf /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadHighway-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadHighway-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadHighway-1@2x.png
statbuf /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadLocalRoad-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadLocalRoad-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/RealisticRoadLocalRoad-1@2x.png
statbuf /private/var/mobile/Library/Caches/GeoServices/Resources/altitude-551.xml
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/altitude-551.xml
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/altitude-551.xml
statbuf /private/var/mobile/Library/Caches/GeoServices/Resources/autonavi-1.png
statbuf /private/var/mobile/Library/Caches/GeoServices/Resources/autonavi-1@2x.png
statbuf /private/var/mobile/Library/Caches/GeoServices/Resources/night-DetailedLandCoverSand-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/night-DetailedLandCoverSand-1@2x.png
engthlstat /private/var/mobile/Library/Caches/GeoServices/Resources/night-DetailedLandCoverSand-1@2x.png
statbuf /private/var/mobile/Library/Carrier Bundles/Overlay
engthlstat /private/var/mobile/Library/Carrier Bundles/Overlay
engthlstat /private/var/mobile/Library/Carrier Bundles/Overlay
statbuf /private/var/mobile/Library/Operator Bundle.bundle
engthlstat /private/var/mobile/Library/Operator Bundle.bundle
engthlstat /private/var/mobile/Library/Operator Bundle.bundle
statbuf /private/var/mobile/Library
engthlstat /private/var/mobile/Library
engthlstat /private/var/mobile/Library
statbuf /private/var/mobile
engthlstat /private/var/mobile
engthlstat /private/var/mobile
statbuf /private/var
engthlstat /private/var
engthlstat /private/var
statbuf /var/db/timezone/localtime
engthlstat /var/db/timezone/localtime
engthlstat /var/db/timezone/localtime
engthlstat /System/Library/CoreServices/SystemVersion.plist
engthlstat /usr/local
engthlstat /usr
engthlstat /usr/local/
engthlstat /private
engthlstat /var/root
engthlstat /var/mobile
engthlstat /var/root/
engthlstat /var/wireless
statbuf /Applications/Cydia.app
statbuf /var/mobile/Library/Caches/com.xxtouch.XXTExplorer
statbuf /Applications/AWZ.app
engthfopen /Applications/AWZ.app
statbuf /Applications/NZT.app
engthfopen /Applications/NZT.app
statbuf /Applications/igvx.app
engthfopen /Applications/igvx.app
statbuf /Applications/TouchElf.app
engthfopen /Applications/TouchElf.app
statbuf /Applications/TouchSprite.app
engthfopen /Applications/TouchSprite.app
statbuf /Applications/WujiVPN.app
engthfopen /Applications/WujiVPN.app
statbuf /Applications/RST.app
engthfopen /Applications/RST.app
statbuf /Applications/Forge9.app
engthfopen /Applications/Forge9.app
statbuf /Applications/Forge.app
engthfopen /Applications/Forge.app
statbuf /Applications/GFaker.app
engthfopen /Applications/GFaker.app
statbuf /Applications/hdfakerset.app
engthfopen /Applications/hdfakerset.app
statbuf /Applications/Pranava.app
engthfopen /Applications/Pranava.app
statbuf /Applications/iG.app
engthfopen /Applications/iG.app
statbuf /Applications/HiddenApi.app
engthfopen /Applications/HiddenApi.app
statbuf /Applications/Xgen.app
engthfopen /Applications/Xgen.app
statbuf /Applications/BirdFaker9.app
engthfopen /Applications/BirdFaker9.app
statbuf /Applications/VPNMasterPro.app
engthfopen /Applications/VPNMasterPro.app
statbuf /Applications/GuizmOVPN.app
engthfopen /Applications/GuizmOVPN.app
statbuf /Applications/OTRLocation.app
engthfopen /Applications/OTRLocation.app
statbuf /Applications/rwx.app
engthfopen /Applications/rwx.app
statbuf /Applications/FakeMyLocation.app
engthfopen /Applications/FakeMyLocation.app
statbuf /Applications/anylocation.app
engthfopen /Applications/anylocation.app
statbuf /Applications/location360pro.app
engthfopen /Applications/location360pro.app
statbuf /Applications/xGPS.app
engthfopen /Applications/xGPS.app
statbuf /Applications/007gaiji.app
engthfopen /Applications/007gaiji.app
statbuf /Applications/ALS.app
engthfopen /Applications/ALS.app
statbuf /Applications/AXJ.app
engthfopen /Applications/AXJ.app
statbuf /Applications/serialudid.app
engthfopen /Applications/serialudid.app
statbuf /Applications/BirdFaker.app
engthfopen /Applications/BirdFaker.app
statbuf /Applications/zorro.app
engthfopen /Applications/zorro.app
statbuf /Applications/YOY.app
engthfopen /Applications/YOY.app
statbuf /System/Library/Frameworks/CFNetwork.framework
statbuf /System/Library/Frameworks/CFNetwork.framework
statbuf /System/Library/Frameworks/CFNetwork.framework/CFNetwork
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Saved Application State
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Saved Application State/com.mhytesssfffkk.savedState
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Saved Application State/com.mhytesssfffkk.savedState/KnownSceneSessions
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
statbuf /private/var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Cookies/Cookies.binarycookies
engthlstat /private/var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Cookies/Cookies.binarycookies_tmp_4306_0.dat
statbuf /private/var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Cookies/Cookies.binarycookies
engthlstat /private/var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Cookies/Cookies.binarycookies_tmp_4306_0.dat
statbuf /var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5
statbuf /private/var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Cookies/Cookies.binarycookies
engthlstat /private/var/mobile/Containers/Data/Application/1F6B0DC5-981A-433D-9DDA-CDF2569594D5/Library/Cookies/Cookies.binarycookies_tmp_4306_0.dat
