-(void)initPathMap:(list *)list{
    // Restrict / by whitelisting
    NSMutableArray *list;
    [list addObject: @""]
    [list addObject:@"/"];
    [list addObject:@"/.file"];
    [list addObject:@"/.ba"];
    [list addObject:@"/.mb"];
    [list addObject:@"/.HFS"];
    [list addObject:@"/.Trashes"];
    // [list addObject:@"/AppleInternal"];
    [list addObject:@"/cores"];
    [list addObject:@"/Developer"];
    [list addObject:@"/lib"];
    [list addObject:@"/mnt"];

    // Restrict /bin by whitelisting
    [list addObject:@"/bin"];
    [list addObject:@"/bin/df"];
    [list addObject:@"/bin/ps"];

    // Restrict /sbin by whitelisting
    [list addObject:@"/sbin"];
    [list addObject:@"/sbin/fsck"];
    [list addObject:@"/sbin/launchd"];
    [list addObject:@"/sbin/mount"];
    [list addObject:@"/sbin/pfctl"];

    // Restrict /Applications by whitelisting
    [list addObject:@"/Applications"];
    [list addObject:@"/Applications/AXUIViewService.app"];
    [list addObject:@"/Applications/AccountAuthenticationDialog.app"];
    [list addObject:@"/Applications/ActivityMessagesApp.app"];
    [list addObject:@"/Applications/AdPlatformsDiagnostics.app"];
    [list addObject:@"/Applications/AppStore.app"];
    [list addObject:@"/Applications/AskPermissionUI.app"];
    [list addObject:@"/Applications/BusinessExtensionsWrapper.app"];
    [list addObject:@"/Applications/CTCarrierSpaceAuth.app"];
    [list addObject:@"/Applications/Camera.app"];
    [list addObject:@"/Applications/CheckerBoard.app"];
    [list addObject:@"/Applications/CompassCalibrationViewService.app"];
    [list addObject:@"/Applications/ContinuityCamera.app"];
    [list addObject:@"/Applications/CoreAuthUI.app"];
    [list addObject:@"/Applications/DDActionsService.app"];
    [list addObject:@"/Applications/DNDBuddy.app"];
    [list addObject:@"/Applications/DataActivation.app"];
    [list addObject:@"/Applications/DemoApp.app"];
    [list addObject:@"/Applications/Diagnostics.app"];
    [list addObject:@"/Applications/DiagnosticsService.app"];
    [list addObject:@"/Applications/FTMInternal-4.app"];
    [list addObject:@"/Applications/Family.app"];
    [list addObject:@"/Applications/Feedback Assistant iOS.app"];
    [list addObject:@"/Applications/FieldTest.app"];
    [list addObject:@"/Applications/FindMyiPhone.app"];
    [list addObject:@"/Applications/FunCameraShapes.app"];
    [list addObject:@"/Applications/FunCameraText.app"];
    [list addObject:@"/Applications/GameCenterUIService.app"];
    [list addObject:@"/Applications/HashtagImages.app"];
    [list addObject:@"/Applications/Health.app"];
    [list addObject:@"/Applications/HealthPrivacyService.app"];
    [list addObject:@"/Applications/HomeUIService.app"];
    [list addObject:@"/Applications/InCallService.app"];
    [list addObject:@"/Applications/Magnifier.app"];
    [list addObject:@"/Applications/MailCompositionService.app"];
    [list addObject:@"/Applications/MessagesViewService.app"];
    [list addObject:@"/Applications/MobilePhone.app"];
    [list addObject:@"/Applications/MobileSMS.app"];
    [list addObject:@"/Applications/MobileSafari.app"];
    [list addObject:@"/Applications/MobileSlideShow.app"];
    [list addObject:@"/Applications/MobileTimer.app"];
    [list addObject:@"/Applications/MusicUIService.app"];
    [list addObject:@"/Applications/Passbook.app"];
    [list addObject:@"/Applications/PassbookUIService.app"];
    [list addObject:@"/Applications/PhotosViewService.app"];
    [list addObject:@"/Applications/PreBoard.app"];
    [list addObject:@"/Applications/Preferences.app"];
    [list addObject:@"/Applications/Print Center.app"];
    [list addObject:@"/Applications/SIMSetupUIService.app"];
    [list addObject:@"/Applications/SLGoogleAuth.app"];
    [list addObject:@"/Applications/SLYahooAuth.app"];
    [list addObject:@"/Applications/SafariViewService.app"];
    [list addObject:@"/Applications/ScreenSharingViewService.app"];
    [list addObject:@"/Applications/ScreenshotServicesService.app"];
    [list addObject:@"/Applications/Setup.app"];
    [list addObject:@"/Applications/SharedWebCredentialViewService.app"];
    [list addObject:@"/Applications/SharingViewService.app"];
    [list addObject:@"/Applications/SiriViewService.app"];
    [list addObject:@"/Applications/SoftwareUpdateUIService.app"];
    [list addObject:@"/Applications/StoreDemoViewService.app"];
    [list addObject:@"/Applications/StoreKitUIService.app"];
    [list addObject:@"/Applications/TrustMe.app"];
    [list addObject:@"/Applications/Utilities"];
    [list addObject:@"/Applications/VideoSubscriberAccountViewService.app"];
    [list addObject:@"/Applications/WLAccessService.app"];
    [list addObject:@"/Applications/Web.app"];
    [list addObject:@"/Applications/WebApp1.appWebApp1.app"];
    [list addObject:@"/Applications/WebContentAnalysisUI.app"];
    [list addObject:@"/Applications/WebSheet.app"];
    [list addObject:@"/Applications/iAdOptOut.app"];
    [list addObject:@"/Applications/iCloud.app"];


    //and special
    [list addObject:@"/var/mobile/Library/Caches/com.xxtouch.XXTExplorer" ];
    [list addObject:@"/Applications/Cydia.app" ];
    [list addObject:@"/Applications/AWZ.app" ];
    [list addObject:@"/Applications/NZT.app" ];
    [list addObject:@"/Applications/igvx.app" ];
    [list addObject:@"/Applications/TouchElf.app" ];
    [list addObject:@"/Applications/TouchSprite.app" ];
    [list addObject:@"/Applications/WujiVPN.app" ];
    [list addObject:@"/Applications/RST.app" ];
    [list addObject:@"/Applications/Forge9.app" ];
    [list addObject:@"/Applications/Forge.app" ];
    [list addObject:@"/Applications/GFaker.app" ];
    [list addObject:@"/Applications/hdfakerset.app" ];
    [list addObject:@"/Applications/BirdFaker9.app" ];
    [list addObject:@"/Applications/Pranava.app" ];
    [list addObject:@"/Applications/hdfakerset.app" ];
    [list addObject:@"/Applications/iG.app" ];
    [list addObject:@"/Applications/HiddenApi.app" ];
    [list addObject:@"/Applications/hdfakerset.app" ];
    [list addObject:@"/Applications/VPNMasterPro.app" ];
    [list addObject:@"/Applications/GuizmOVPN.app" ];
    [list addObject:@"/Applications/OTRLocation.app" ];
    [list addObject:@"/Applications/rwx.app" ];
    [list addObject:@"/Applications/FakeMyLocation.app" ];
    [list addObject:@"/Applications/anylocation.app" ];
    [list addObject:@"/Applications/location360pro.app" ];
    [list addObject:@"/Applications/xGPS.app" ];
    [list addObject:@"/Applications/007gaiji.app" ];
    [list addObject:@"/Applications/ALS.app" ];
    [list addObject:@"/Applications/AXJ.app" ];
    [list addObject:@"/Applications/serialudid.app" ];
    [list addObject:@"/Applications/BirdFaker.app" ];
    [list addObject:@"/Applications/zorro.app" ];
    [list addObject:@"/Applications/YOY.app" ];
    [list addObject:@"/Applications/Cydia.app" ];
    [list addObject:@"/Applications/RootApp.app" ];
    [list addObject:@"/private/var/lib/apt/" ];

    [list addObject:@"/private/var/db/systemstats/" ];
    [list addObject:@"/private/var/db/systemstats/last_boot_uuid" ];
    [list addObject:@"/private/var/db/systemstats/current_boot_uuid" ];
    [list addObject:@"/private/var/db/systemstats/fseventsd-uuid" ];
    [list addObject:@"/private/var/lib/apt/" ];
//    [list addObject:@"/System/Library/PrivateFrameworks/CoreMaterial.framework/Info.plist" ];



    // Restrict /dev
    [list addObject:@"/dev"];
    [list addObject:@"/dev/dlci." ];
    [list addObject:@"/dev/vn0" ];
    [list addObject:@"/dev/vn1" ];
    [list addObject:@"/dev/kmem" ];
    [list addObject:@"/dev/mem" ];

    // Restrict /private by whitelisting
    [list addObject:@"/private"];
    [list addObject:@"/private/etc"];
    [list addObject:@"/private/system_data"];
    [list addObject:@"/private/var"];
    [list addObject:@"/private/xarts"];

    // Restrict /etc by whitelisting
    [list addObject:@"/etc"];
    [list addObject:@"/etc/asl"];
    [list addObject:@"/etc/asl.conf"];
    [list addObject:@"/etc/fstab"];
    [list addObject:@"/etc/group"];
    [list addObject:@"/etc/hosts"];
    [list addObject:@"/etc/hosts.equiv"];
    [list addObject:@"/etc/master.passwd"];
    [list addObject:@"/etc/networks"];
    [list addObject:@"/etc/notify.conf"];
    [list addObject:@"/etc/passwd"];
    [list addObject:@"/etc/ppp"];
    [list addObject:@"/etc/protocols"];
    [list addObject:@"/etc/racoon"];
    [list addObject:@"/etc/services"];
    [list addObject:@"/etc/ttys"];

    // Restrict /Library by whitelisting
    [list addObject:@"/Library"];
    [list addObject:@"/Library/Application Support"];
    [list addObject:@"/Library/Application Support/AggregateDictionary"];
    [list addObject:@"/Library/Application Support/BTServer"];
    [list addObject:@"/Library/Audio"];
    [list addObject:@"/Library/Caches"];
    [list addObject:@"/Library/Caches/cy-" ];
    [list addObject:@"/Library/Filesystems"];
    [list addObject:@"/Library/Internet Plug-Ins"];
    [list addObject:@"/Library/Keychains"];
    [list addObject:@"/Library/LaunchAgents"];
    [list addObject:@"/Library/LaunchDaemons"];
    [list addObject:@"/Library/Logs"];
    [list addObject:@"/Library/Managed Preferences"];
    [list addObject:@"/Library/MobileDevice"];
    [list addObject:@"/Library/MusicUISupport"];
    [list addObject:@"/Library/Preferences"];
    [list addObject:@"/Library/Printers"];
    [list addObject:@"/Library/Ringtones"];
    [list addObject:@"/Library/Updates"];
    [list addObject:@"/Library/Wallpaper"];

    // Restrict /tmp
    [list addObject:@"/tmp"];
    [list addObject:@"/tmp/com.apple"];
    [list addObject:@"/tmp/substrate" ];
    [list addObject:@"/tmp/Substrate" ];
    [list addObject:@"/tmp/cydia.log" ];
    [list addObject:@"/tmp/syslog" ];
    [list addObject:@"/tmp/slide.txt" ];
    [list addObject:@"/tmp/amfidebilitate.out" ];
    [list addObject:@"/tmp/org.coolstar" ];
    [list addObject:@"/tmp/amfid_payload.alive" ];
    [list addObject:@"/tmp/jailbreakd.pid" ];

    // Restrict /var by whitelisting
    [list addObject:@"/var"];
    [list addObject:@"/var/.DocumentRevisions"];
    [list addObject:@"/var/.fseventsd"];
    [list addObject:@"/var/.overprovisioning_file"];
    [list addObject:@"/var/audit"];
    [list addObject:@"/var/backups"];
    [list addObject:@"/var/buddy"];
    [list addObject:@"/var/containers"];
    [list addObject:@"/var/containers/Bundle"];
    [list addObject:@"/var/containers/Bundle/Application"];
    [list addObject:@"/var/containers/Bundle/Framework"];
    [list addObject:@"/var/containers/Bundle/PluginKitPlugin"];
    [list addObject:@"/var/containers/Bundle/VPNPlugin"];
    [list addObject:@"/var/cores"];
    [list addObject:@"/var/db"];
    [list addObject:@"/var/db/stash" ];
    [list addObject:@"/var/ea"];
    [list addObject:@"/var/empty"];
    [list addObject:@"/var/folders"];
    [list addObject:@"/var/hardware"];
    [list addObject:@"/var/installd"];
    [list addObject:@"/var/internal"];
    [list addObject:@"/var/keybags"];
    [list addObject:@"/var/Keychains"];
    [list addObject:@"/var/lib"];
    [list addObject:@"/var/local"];
    [list addObject:@"/var/lock"];
    [list addObject:@"/var/log"];
    [list addObject:@"/var/log/asl"];
    [list addObject:@"/var/log/com.apple.xpc.launchd"];
    [list addObject:@"/var/log/corecaptured.log"];
    [list addObject:@"/var/log/ppp"];
    [list addObject:@"/var/log/ppp.log"];
    [list addObject:@"/var/log/racoon.log"];
    [list addObject:@"/var/log/sa"];
    [list addObject:@"/var/logs"];
    [list addObject:@"/var/Managed Preferences"];
    [list addObject:@"/var/MobileAsset"];
    [list addObject:@"/var/MobileDevice"];
    [list addObject:@"/var/MobileSoftwareUpdate"];
    [list addObject:@"/var/msgs"];
    [list addObject:@"/var/networkd"];
    [list addObject:@"/var/preferences"];
    [list addObject:@"/var/root"];
    [list addObject:@"/var/run"];
    [list addObject:@"/var/run/lockdown"];
    [list addObject:@"/var/run/lockdown.sock"];
    [list addObject:@"/var/run/lockdown_first_run"];
    [list addObject:@"/var/run/mDNSResponder"];
    [list addObject:@"/var/run/printd"];
    [list addObject:@"/var/run/syslog"];
    [list addObject:@"/var/run/syslog.pid"];
    [list addObject:@"/var/run/utmpx"];
    [list addObject:@"/var/run/vpncontrol.sock"];
    [list addObject:@"/var/run/asl_input"];
    [list addObject:@"/var/run/configd.pid"];
    [list addObject:@"/var/run/lockbot"];
    [list addObject:@"/var/run/pppconfd"];
    [list addObject:@"/var/run/fudinit"];
    [list addObject:@"/var/spool"];
    [list addObject:@"/var/staged_system_apps"];
    [list addObject:@"/var/tmp"];
    [list addObject:@"/var/vm"];
    [list addObject:@"/var/wireless"];

    // Restrict /var/mobile by whitelisting
    [list addObject:@"/var/mobile"];
    [list addObject:@"/var/mobile/Applications"];
    [list addObject:@"/var/mobile/Containers"];
    [list addObject:@"/var/mobile/Containers/Data"];
    [list addObject:@"/var/mobile/Containers/Data/Application"];
    [list addObject:@"/var/mobile/Containers/Data/InternalDaemon"];
    [list addObject:@"/var/mobile/Containers/Data/PluginKitPlugin"];
    [list addObject:@"/var/mobile/Containers/Data/TempDir"];
    [list addObject:@"/var/mobile/Containers/Data/VPNPlugin"];
    [list addObject:@"/var/mobile/Containers/Data/XPCService"];
    [list addObject:@"/var/mobile/Containers/Shared"];
    [list addObject:@"/var/mobile/Containers/Shared/AppGroup"];
    [list addObject:@"/var/mobile/Documents"];
    [list addObject:@"/var/mobile/Downloads"];
    [list addObject:@"/var/mobile/Library"];
    [list addObject:@"/var/mobile/Library/Caches"];
    [list addObject:@"/var/mobile/Library/Caches/com.apple"];
    [list addObject:@"/var/mobile/Library/Caches/.com.apple"];
    [list addObject:@"/var/mobile/Library/Caches/AdMob"];
    [list addObject:@"/var/mobile/Library/Caches/AccountMigrationInProgress"];
    [list addObject:@"/var/mobile/Library/Caches/ACMigrationLock"];
    [list addObject:@"/var/mobile/Library/Caches/BTAvrcp"];
    [list addObject:@"/var/mobile/Library/Caches/cache"];
    [list addObject:@"/var/mobile/Library/Caches/Checkpoint.plist"];
    [list addObject:@"/var/mobile/Library/Caches/ckkeyrolld"];
    [list addObject:@"/var/mobile/Library/Caches/CloudKit"];
    [list addObject:@"/var/mobile/Library/Caches/DateFormats.plist"];
    [list addObject:@"/var/mobile/Library/Caches/FamilyCircle"];
    [list addObject:@"/var/mobile/Library/Caches/GameKit"];
    [list addObject:@"/var/mobile/Library/Caches/GeoServices"];
    [list addObject:@"/var/mobile/Library/Caches/AccountMigrationInProgress"];
    [list addObject:@"/var/mobile/Library/Caches/MappedImageCache"];
    [list addObject:@"/var/mobile/Library/Caches/OTACrashCopier"];
    [list addObject:@"/var/mobile/Library/Caches/PassKit"];
    [list addObject:@"/var/mobile/Library/Caches/rtcreportingd"];
    [list addObject:@"/var/mobile/Library/Caches/sharedCaches"];
    [list addObject:@"/var/mobile/Library/Caches/Snapshots"];
    [list addObject:@"/var/mobile/Library/Caches/Snapshots/com.apple"];
    [list addObject:@"/var/mobile/Library/Caches/TelephonyUI"];
    [list addObject:@"/var/mobile/Library/Caches/Weather"];
    [list addObject:@"/var/mobile/Library/ControlCenter"];
    [list addObject:@"/var/mobile/Library/ControlCenter/ModuleConfiguration.plist"];
    [list addObject:@"/var/mobile/Library/Cydia" ];
    [list addObject:@"/var/mobile/Library/Logs/Cydia" ];
    [list addObject:@"/var/mobile/Library/SBSettings" ];
    [list addObject:@"/var/mobile/Library/Sileo" ];
    [list addObject:@"/var/mobile/Library/Preferences"];
    [list addObject:@"/var/mobile/Library/Preferences/com.apple."];
    [list addObject:@"/var/mobile/Library/Preferences/.GlobalPreferences.plist"];
    [list addObject:@"/var/mobile/Library/Preferences/ckkeyrolld.plist"];
    [list addObject:@"/var/mobile/Library/Preferences/nfcd.plist"];
    [list addObject:@"/var/mobile/Library/Preferences/UITextInputContextIdentifiers.plist"];
    [list addObject:@"/var/mobile/Library/Preferences/Wallpaper.png"];
    [list addObject:@"/var/mobile/Media"];
    [list addObject:@"/var/mobile/MobileSoftwareUpdate"];

    // Restrict /usr by whitelisting
    [list addObject:@"/usr"];
    [list addObject:@"/usr/bin"];
    [list addObject:@"/usr/bin/DumpBasebandCrash"];
    [list addObject:@"/usr/bin/PerfPowerServicesExtended"];
    [list addObject:@"/usr/bin/abmlite"];
    [list addObject:@"/usr/bin/brctl"];
    [list addObject:@"/usr/bin/footprint"];
    [list addObject:@"/usr/bin/hidutil"];
    [list addObject:@"/usr/bin/hpmdiagnose"];
    [list addObject:@"/usr/bin/kbdebug"];
    [list addObject:@"/usr/bin/powerlogHelperd"];
    [list addObject:@"/usr/bin/sysdiagnose"];
    [list addObject:@"/usr/bin/tailspin"];
    [list addObject:@"/usr/bin/taskinfo"];
    [list addObject:@"/usr/bin/vm_stat"];
    [list addObject:@"/usr/bin/zprint"];

    if([list useTweakCompatibilityMode] ) {
        [list addObject:@"/usr/lib"];
        [list addObject:@"/usr/lib/libsubstrate" ];
        [list addObject:@"/usr/lib/libsubstitute" ];
        [list addObject:@"/usr/lib/libSubstitrate" ];
        [list addObject:@"/usr/lib/TweakInject" ];
        [list addObject:@"/usr/lib/substrate" ];
        [list addObject:@"/usr/lib/tweaks" ];
        [list addObject:@"/usr/lib/apt" ];
        [list addObject:@"/usr/lib/bash" ];
        [list addObject:@"/usr/lib/cycript" ];
        [list addObject:@"/usr/lib/libmis.dylib" ];
    } else {
        [list addObject:@"/usr/lib"];
        [list addObject:@"/usr/lib/FDRSealingMap.plist"];
        [list addObject:@"/usr/lib/bbmasks"];
        [list addObject:@"/usr/lib/dyld"];
        [list addObject:@"/usr/lib/libCRFSuite"];
        [list addObject:@"/usr/lib/libDHCPServer"];
        [list addObject:@"/usr/lib/libMatch"];
        [list addObject:@"/usr/lib/libSystem"];
        [list addObject:@"/usr/lib/libarchive"];
        [list addObject:@"/usr/lib/libbsm"];
        [list addObject:@"/usr/lib/libbz2"];
        [list addObject:@"/usr/lib/libc++"];
        [list addObject:@"/usr/lib/libc"];
        [list addObject:@"/usr/lib/libcharset"];
        [list addObject:@"/usr/lib/libcurses"];
        [list addObject:@"/usr/lib/libdbm"];
        [list addObject:@"/usr/lib/libdl"];
        [list addObject:@"/usr/lib/libeasyperf"];
        [list addObject:@"/usr/lib/libedit"];
        [list addObject:@"/usr/lib/libexslt"];
        [list addObject:@"/usr/lib/libextension"];
        [list addObject:@"/usr/lib/libform"];
        [list addObject:@"/usr/lib/libiconv"];
        [list addObject:@"/usr/lib/libicucore"];
        [list addObject:@"/usr/lib/libinfo"];
        [list addObject:@"/usr/lib/libipsec"];
        [list addObject:@"/usr/lib/liblzma"];
        [list addObject:@"/usr/lib/libm"];
        [list addObject:@"/usr/lib/libmecab"];
        [list addObject:@"/usr/lib/libncurses"];
        [list addObject:@"/usr/lib/libobjc"];
        [list addObject:@"/usr/lib/libpcap"];
        [list addObject:@"/usr/lib/libpmsample"];
        [list addObject:@"/usr/lib/libpoll"];
        [list addObject:@"/usr/lib/libproc"];
        [list addObject:@"/usr/lib/libpthread"];
        [list addObject:@"/usr/lib/libresolv"];
        [list addObject:@"/usr/lib/librpcsvc"];
        [list addObject:@"/usr/lib/libsandbox"];
        [list addObject:@"/usr/lib/libsqlite3"];
        [list addObject:@"/usr/lib/libstdc++"];
        [list addObject:@"/usr/lib/libtidy"];
        [list addObject:@"/usr/lib/libutil"];
        [list addObject:@"/usr/lib/libxml2"];
        [list addObject:@"/usr/lib/libxslt"];
        [list addObject:@"/usr/lib/libz"];
        [list addObject:@"/usr/lib/libperfcheck"];
        [list addObject:@"/usr/lib/libedit"];
        [list addObject:@"/usr/lib/log"];
        [list addObject:@"/usr/lib/system"];
        [list addObject:@"/usr/lib/updaters"];
        [list addObject:@"/usr/lib/xpc"];
    }

    [list addObject:@"/usr/libexec"];
    [list addObject:@"/usr/libexec/BackupAgent"];
    [list addObject:@"/usr/libexec/BackupAgent2"];
    [list addObject:@"/usr/libexec/CrashHousekeeping"];
    [list addObject:@"/usr/libexec/DataDetectorsSourceAccess"];
    [list addObject:@"/usr/libexec/FSTaskScheduler"];
    [list addObject:@"/usr/libexec/FinishRestoreFromBackup"];
    [list addObject:@"/usr/libexec/IOAccelMemoryInfoCollector"];
    [list addObject:@"/usr/libexec/IOMFB_bics_daemon"];
    [list addObject:@"/usr/libexec/Library"];
    [list addObject:@"/usr/libexec/MobileGestaltHelper"];
    [list addObject:@"/usr/libexec/MobileStorageMounter"];
    [list addObject:@"/usr/libexec/NANDTaskScheduler"];
    [list addObject:@"/usr/libexec/OTATaskingAgent"];
    [list addObject:@"/usr/libexec/PowerUIAgent"];
    [list addObject:@"/usr/libexec/PreboardService"];
    [list addObject:@"/usr/libexec/ProxiedCrashCopier"];
    [list addObject:@"/usr/libexec/PurpleReverseProxy"];
    [list addObject:@"/usr/libexec/ReportMemoryException"];
    [list addObject:@"/usr/libexec/SafariCloudHistoryPushAgent"];
    [list addObject:@"/usr/libexec/SidecarRelay"];
    [list addObject:@"/usr/libexec/SyncAgent"];
    [list addObject:@"/usr/libexec/UserEventAgent"];
    [list addObject:@"/usr/libexec/addressbooksyncd"];
    [list addObject:@"/usr/libexec/adid"];
    [list addObject:@"/usr/libexec/adprivacyd"];
    [list addObject:@"/usr/libexec/adservicesd"];
    [list addObject:@"/usr/libexec/afcd"];
    [list addObject:@"/usr/libexec/airtunesd"];
    [list addObject:@"/usr/libexec/amfid"];
    [list addObject:@"/usr/libexec/asd"];
    [list addObject:@"/usr/libexec/assertiond"];
    [list addObject:@"/usr/libexec/atc"];
    [list addObject:@"/usr/libexec/atwakeup"];
    [list addObject:@"/usr/libexec/backboardd"];
    [list addObject:@"/usr/libexec/biometrickitd"];
    [list addObject:@"/usr/libexec/bootpd"];
    [list addObject:@"/usr/libexec/bulletindistributord"];
    [list addObject:@"/usr/libexec/captiveagent"];
    [list addObject:@"/usr/libexec/cc_fips_test"];
    [list addObject:@"/usr/libexec/checkpointd"];
    [list addObject:@"/usr/libexec/cloudpaird"];
    [list addObject:@"/usr/libexec/com.apple.automation.defaultslockdownserviced"];
    [list addObject:@"/usr/libexec/companion_proxy"];
    [list addObject:@"/usr/libexec/configd"];
    [list addObject:@"/usr/libexec/corecaptured"];
    [list addObject:@"/usr/libexec/coreduetd"];
    [list addObject:@"/usr/libexec/crash_mover"];
    [list addObject:@"/usr/libexec/dasd"];
    [list addObject:@"/usr/libexec/demod"];
    [list addObject:@"/usr/libexec/demod_helper"];
    [list addObject:@"/usr/libexec/dhcpd"];
    [list addObject:@"/usr/libexec/diagnosticd"];
    [list addObject:@"/usr/libexec/diagnosticextensionsd"];
    [list addObject:@"/usr/libexec/dmd"];
    [list addObject:@"/usr/libexec/dprivacyd"];
    [list addObject:@"/usr/libexec/dtrace"];
    [list addObject:@"/usr/libexec/duetexpertd"];
    [list addObject:@"/usr/libexec/eventkitsyncd"];
    [list addObject:@"/usr/libexec/fdrhelper"];
    [list addObject:@"/usr/libexec/findmydeviced"];
    [list addObject:@"/usr/libexec/finish_demo_restore"];
    [list addObject:@"/usr/libexec/fmfd"];
    [list addObject:@"/usr/libexec/fmflocatord"];
    [list addObject:@"/usr/libexec/fseventsd"];
    [list addObject:@"/usr/libexec/ftp-proxy"];
    [list addObject:@"/usr/libexec/gamecontrollerd"];
    [list addObject:@"/usr/libexec/gamed"];
    [list addObject:@"/usr/libexec/gpsd"];
    [list addObject:@"/usr/libexec/hangreporter"];
    [list addObject:@"/usr/libexec/hangtracerd"];
    [list addObject:@"/usr/libexec/heartbeatd"];
    [list addObject:@"/usr/libexec/hostapd"];
    [list addObject:@"/usr/libexec/idamd"];
    [list addObject:@"/usr/libexec/init_data_protection -> seputil"];
    [list addObject:@"/usr/libexec/installd"];
    [list addObject:@"/usr/libexec/ioupsd"];
    [list addObject:@"/usr/libexec/keybagd"];
    [list addObject:@"/usr/libexec/languageassetd"];
    [list addObject:@"/usr/libexec/locationd"];
    [list addObject:@"/usr/libexec/lockdownd"];
    [list addObject:@"/usr/libexec/logd"];
    [list addObject:@"/usr/libexec/lsd"];
    [list addObject:@"/usr/libexec/lskdd"];
    [list addObject:@"/usr/libexec/lskdmsed"];
    [list addObject:@"/usr/libexec/magicswitchd"];
    [list addObject:@"/usr/libexec/mc_mobile_tunnel"];
    [list addObject:@"/usr/libexec/microstackshot"];
    [list addObject:@"/usr/libexec/misagent"];
    [list addObject:@"/usr/libexec/misd"];
    [list addObject:@"/usr/libexec/mmaintenanced"];
    [list addObject:@"/usr/libexec/mobile_assertion_agent"];
    [list addObject:@"/usr/libexec/mobile_diagnostics_relay"];
    [list addObject:@"/usr/libexec/mobile_house_arrest"];
    [list addObject:@"/usr/libexec/mobile_installation_proxy"];
    [list addObject:@"/usr/libexec/mobile_obliterator"];
    [list addObject:@"/usr/libexec/mobile_storage_proxy"];
    [list addObject:@"/usr/libexec/mobileactivationd"];
    [list addObject:@"/usr/libexec/mobileassetd"];
    [list addObject:@"/usr/libexec/mobilewatchdog"];
    [list addObject:@"/usr/libexec/mtmergeprops"];
    [list addObject:@"/usr/libexec/nanomediaremotelinkagent"];
    [list addObject:@"/usr/libexec/nanoregistryd"];
    [list addObject:@"/usr/libexec/nanoregistrylaunchd"];
    [list addObject:@"/usr/libexec/neagent"];
    [list addObject:@"/usr/libexec/nehelper"];
    [list addObject:@"/usr/libexec/nesessionmanager"];
    [list addObject:@"/usr/libexec/networkserviceproxy"];
    [list addObject:@"/usr/libexec/nfcd"];
    [list addObject:@"/usr/libexec/nfrestore_service"];
    [list addObject:@"/usr/libexec/nlcd"];
    [list addObject:@"/usr/libexec/notification_proxy"];
    [list addObject:@"/usr/libexec/nptocompaniond"];
    [list addObject:@"/usr/libexec/nsurlsessiond"];
    [list addObject:@"/usr/libexec/nsurlstoraged"];
    [list addObject:@"/usr/libexec/online-auth-agent"];
    [list addObject:@"/usr/libexec/oscard"];
    [list addObject:@"/usr/libexec/pcapd"];
    [list addObject:@"/usr/libexec/pcsstatus"];
    [list addObject:@"/usr/libexec/pfd"];
    [list addObject:@"/usr/libexec/pipelined"];
    [list addObject:@"/usr/libexec/pkd"];
    [list addObject:@"/usr/libexec/pkreporter"];
    [list addObject:@"/usr/libexec/ptpd"];
    [list addObject:@"/usr/libexec/rapportd"];
    [list addObject:@"/usr/libexec/replayd"];
    [list addObject:@"/usr/libexec/resourcegrabberd"];
    [list addObject:@"/usr/libexec/rolld"];
    [list addObject:@"/usr/libexec/routined"];
    [list addObject:@"/usr/libexec/rtbuddyd"];
    [list addObject:@"/usr/libexec/rtcreportingd"];
    [list addObject:@"/usr/libexec/safarifetcherd"];
    [list addObject:@"/usr/libexec/screenshotsyncd"];
    [list addObject:@"/usr/libexec/security-sysdiagnose"];
    [list addObject:@"/usr/libexec/securityd"];
    [list addObject:@"/usr/libexec/securityuploadd"];
    [list addObject:@"/usr/libexec/seld"];
    [list addObject:@"/usr/libexec/seputil"];
    [list addObject:@"/usr/libexec/sharingd"];
    [list addObject:@"/usr/libexec/signpost_reporter"];
    [list addObject:@"/usr/libexec/silhouette"];
    [list addObject:@"/usr/libexec/siriknowledged"];
    [list addObject:@"/usr/libexec/smcDiagnose"];
    [list addObject:@"/usr/libexec/splashboardd"];
    [list addObject:@"/usr/libexec/springboardservicesrelay"];
    [list addObject:@"/usr/libexec/streaming_zip_conduit"];
    [list addObject:@"/usr/libexec/swcd"];
    [list addObject:@"/usr/libexec/symptomsd"];
    [list addObject:@"/usr/libexec/symptomsd-helper"];
    [list addObject:@"/usr/libexec/sysdiagnose_helper"];
    [list addObject:@"/usr/libexec/sysstatuscheck"];
    [list addObject:@"/usr/libexec/tailspind"];
    [list addObject:@"/usr/libexec/timed"];
    [list addObject:@"/usr/libexec/tipsd"];
    [list addObject:@"/usr/libexec/topicsmap.db"];
    [list addObject:@"/usr/libexec/transitd"];
    [list addObject:@"/usr/libexec/trustd"];
    [list addObject:@"/usr/libexec/tursd"];
    [list addObject:@"/usr/libexec/tzd"];
    [list addObject:@"/usr/libexec/tzinit"];
    [list addObject:@"/usr/libexec/tzlinkd"];
    [list addObject:@"/usr/libexec/videosubscriptionsd"];
    [list addObject:@"/usr/libexec/wapic"];
    [list addObject:@"/usr/libexec/wcd"];
    [list addObject:@"/usr/libexec/webbookmarksd"];
    [list addObject:@"/usr/libexec/webinspectord"];
    [list addObject:@"/usr/libexec/wifiFirmwareLoader"];
    [list addObject:@"/usr/libexec/wifivelocityd"];
    [list addObject:@"/usr/libexec/xpcproxy"];
    [list addObject:@"/usr/libexec/xpcroleaccountd"];
    [list addObject:@"/usr/local"];
    [list addObject:@"/usr/local/bin"];
    [list addObject:@"/usr/local/lib"];
    [list addObject:@"/usr/local/standalone"];
    [list addObject:@"/usr/sbin"];
    [list addObject:@"/usr/sbin/BTAvrcp"];
    [list addObject:@"/usr/sbin/BTLEServer"];
    [list addObject:@"/usr/sbin/BTMap"];
    [list addObject:@"/usr/sbin/BTPbap"];
    [list addObject:@"/usr/sbin/BlueTool"];
    [list addObject:@"/usr/sbin/WiFiNetworkStoreModel.momd"];
    [list addObject:@"/usr/sbin/WirelessRadioManagerd"];
    [list addObject:@"/usr/sbin/absd"];
    [list addObject:@"/usr/sbin/addNetworkInterface"];
    [list addObject:@"/usr/sbin/applecamerad"];
    [list addObject:@"/usr/sbin/aslmanager"];
    [list addObject:@"/usr/sbin/bluetoothd"];
    [list addObject:@"/usr/sbin/cfprefsd"];
    [list addObject:@"/usr/sbin/ckksctl"];
    [list addObject:@"/usr/sbin/distnoted"];
    [list addObject:@"/usr/sbin/fairplayd.H2"];
    [list addObject:@"/usr/sbin/filecoordinationd"];
    [list addObject:@"/usr/sbin/ioreg"];
    [list addObject:@"/usr/sbin/ipconfig"];
    [list addObject:@"/usr/sbin/mDNSResponder"];
    [list addObject:@"/usr/sbin/mDNSResponderHelper"];
    [list addObject:@"/usr/sbin/mediaserverd"];
    [list addObject:@"/usr/sbin/notifyd"];
    [list addObject:@"/usr/sbin/nvram"];
    [list addObject:@"/usr/sbin/pppd"];
    [list addObject:@"/usr/sbin/racoon"];
    [list addObject:@"/usr/sbin/rtadvd"];
    [list addObject:@"/usr/sbin/scutil"];
    [list addObject:@"/usr/sbin/spindump"];
    [list addObject:@"/usr/sbin/syslogd"];
    [list addObject:@"/usr/sbin/wifid"];
    [list addObject:@"/usr/sbin/wirelessproxd"];
    [list addObject:@"/usr/share"];
    [list addObject:@"/usr/share/com.apple.languageassetd"];
    [list addObject:@"/usr/share/CSI"];
    [list addObject:@"/usr/share/firmware"];
    [list addObject:@"/usr/share/icu"];
    [list addObject:@"/usr/share/langid"];
    [list addObject:@"/usr/share/locale"];
    [list addObject:@"/usr/share/mecabra"];
    [list addObject:@"/usr/share/misc"];
    [list addObject:@"/usr/share/progressui"];
    [list addObject:@"/usr/share/tokenizer"];
    [list addObject:@"/usr/share/zoneinfo"];
    [list addObject:@"/usr/share/zoneinfo.default"];
    [list addObject:@"/usr/standalone"];

    // Restrict /System
    [list addObject:@"/System"];
    [list addObject:@"/System/Library/PreferenceBundles/AppList.bundle" ];
}
